### ISSUE TITLE
'Unknown constant: 18' during scanning

### ISSUE THREAD

**Issue by willemsrb** [willemsrb/sonar-jdepend-plugin#2]

**Comment by willemsrb** [comment]
It seems the Unknown constant: 18 is from the contant pool. Types 15, 16 and 18 seems not to be supported in the release version 2.9.1. However according to the source files of the Jdepend repository (https://github.com/clarkware/jdepend) java 8 should be supported. However it seems the last release stems from 2008.

**Comment by willemsrb** [comment]
I'm not sure about keeping on using the Jdepend library now. I'll release the first plugin version and investigate further.

**Comment by willemsrb** [comment]
I'll pull in the sources from the jDepend library voor version 1.1. after releasing v1.0. Most work will go into cleanign up the source to comply with QA standards.

**Comment by willemsrb** [comment]
Found a maintained fork that is updated; https://github.com/nidi3/jdepend

**Comment by sebastian-r** [comment]
In the readme you stated version 1.1 will contain the fix. Do you know when it will be released?
SonarQube only shows version 1.0.

**Comment by willemsrb** [comment]
Hi Sebastian,

unfortunately i've neglected the update a little (well, a lot to be honest). At this moment i'm extending the test suite to convince myself all package references are analyzed correctly. When i've completed that the next version should be released soon.

Regards,
Robert

**Comment by sebastian-r** [comment]
Hi Robert, I am very much looking forward to that :)

**Comment by sebastian-r** [comment]
Can I somehow support you?

**Comment by willemsrb** [comment]
I've decided i will release the plugin containing the updated fork without being able to test everything i wish to test.; i'm having too little time to get the coverage (and solve the problems).

**Comment by willemsrb** [comment]
Closing this issue as a new version has been released. I however would like to point you to (https://github.com/willemsrb/sonar-packageanalyzer-plugin). There i've created a new plugin that does not use jDepend but replicates the functionality. It is based on the Java Parser that SonarQube uses for the Java plugin and can detect many more class usages than jDepend.
