### ISSUE TITLE
A Jdepend-based rule needs to be active for metrics to appear

### ISSUE THREAD

**Issue by akafred** [willemsrb/sonar-jdepend-plugin#7]
I have set up SonarCube 6.3.1 (build 21392) with the Jdepend-plugin version 1.1.1. I have also added package-info.java-files (as you can see below there are none missing). 

However - the Jdepend section shows 0 afferent or efferent couplings - which I find a little strange - does this mean 0 violations or is there something wrong with the analysis? How can I find out more about what is wrong?

![Jdepend analysis result](https://user-images.githubusercontent.com/145701/27334116-8873967a-55c8-11e7-834e-528556b78d89.png)

**Comment by willemsrb** [comment]
Hi @akafred ,

sorry for the late answer; but could you look if you have enabled any rules from the plugin? I suspect that the `descriptor.createIssuesForRuleRepositories(Rules.REPOSITORY);` is used by the optimizer to completly skip the sensor (and thus the metrics). The packages sensor is a separate sensor that does not have that descriptor definition in it.

Regards,
Robert

**Comment by akafred** [comment]
I activated a rule about Afferent Couplings and then I got metrics. 

If it is possible to change the behavior so one can get metrics without activating rules that would probably be less confusing.

**Comment by willemsrb** [comment]
Yes, i will remove the dependency on the rules.

**Comment by willemsrb** [comment]
Should be fixed in next release
