### ISSUE TITLE
package-info.java-maintenance

### ISSUE THREAD

**Issue by akafred** [willemsrb/sonar-jdepend-plugin#8]
The plugin is dependent on the existence of package-info.java-files. However most projects don't maintain these files - so it feels a bit cumbersome...

_Is there a way to avoid or "fake" the existence of these so we don't have to create these almost empty files?_

----

For my own maven-based project I am doing a workaround/hack:

I use this plugin:
```xml
                <plugin>
                    <groupId>de.shadowhunt.maven.plugins</groupId>
                    <artifactId>package-info-maven-plugin</artifactId>
                    <version>2.0.0</version>
                </plugin>
```

in a `sonar`-profile only used on the build server. The plugin has the following configuration:

```xml
                    <plugin>
                        <!-- We generate package-info.java-files to get information from Jdepend in Sonar -->
                        <groupId>de.shadowhunt.maven.plugins</groupId>
                        <artifactId>package-info-maven-plugin</artifactId>
                        <configuration>
                            <packages>
                                <package>
                                </package>
                            </packages>
                            <!-- Sonar doesn't like the files to be in generated-sources :-(
                                 so we have to put them in src-folder - however we don't check them in -->
                            <outputDirectory>${project.basedir}/src/main/java</outputDirectory>
                        </configuration>
                        <executions>
                            <execution>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>package-info</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
```
The files are ignored in `.gitignore`:
```
**/src/**/package-info.java
```
This works, but I would love to not have to do this ....

**Comment by willemsrb** [comment]
Hi @akafred ,

i was working on a plugin that has the same functionality as this plugin, but is not based on the jDepend library (https://github.com/willemsrb/sonar-packageanalyzer-plugin). That plugin also supports reporting the issues on classes. Due to the way the filesystem is used in this plugin that functionality can't be copied easily to this plugin.

Thanks for posting a workaround. I'll update the documentation to mention it.

Regards,
Robert
